# Generated by Django 2.1.7 on 2020-09-12 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='votes_total',
            new_name='reads_current',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='hunter',
            new_name='user_current',
        ),
        migrations.RemoveField(
            model_name='product',
            name='icon',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='pub_date',
        ),
        migrations.RemoveField(
            model_name='product',
            name='url',
        ),
        migrations.AddField(
            model_name='product',
            name='reads_total',
            field=models.IntegerField(default=1),
        ),
    ]
