# Generated by Django 2.1.7 on 2020-09-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_postview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='reads_current',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='reads_total',
            field=models.IntegerField(default=0),
        ),
    ]
